[connection]
host = "raspberrypi.local"
port = 20301
# Generate new token: openssl rand -base64 64
token = "54hhmu7ruiHMYkNACx8LmSkQOdE1dKUDoHgaQRjZ7ClAfJ8qJYkTrO9U9EDX7Yht"

[heartbeat]
# How often to send a heart beat in milliseconds.
interval = 150
# Hhow many beats may be missed before remote car is forced to stop.
missed_beats = 6

[video]
# Height and width of frame.
resolution = [600, 800]
max_framerate = 25  # FPS
device = "/dev/video0"

[controller]
