[connection]
host = "raspberrypi.local"
port = 20301
# Generate: openssl rand -base64 64
token = "YizfFg1UG4xYnijgz6vs8OTwJtJfyRqQJQBnSz9blqkg8Nd1THrz44HbCbA9wsJa"

[heartbeat]
# how often to send a heart beat in milliseconds
interval = 150
# how many beats may be missed before remote car is forced to stop
missed_beats = 6

[video]
# Height and width of frame.
resolution = [600, 800]
max_framerate = 60  # FPS
device = "/dev/video0"

dynamic_framerate = true
min_framerate = 30  # FPS

dynamic_resolution = true
min_resolution = [320, 180]
