[package]
name = "server"
version = "0.1.0"
authors = ["Serhii Babak <mermoldy@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.9"
serde = { version = "1.0", features = ["derive"] }
bincode = "*"
common = { path = "../common" }
log = "0.4.0"
env_logger = "0.7.1"
sysfs_gpio = "0.5"